// Regenerates THIRD_PARTY_NOTICES.md from the licenses of the packages that
// end up in dist/ (bundled code and copied assets). Run: node scripts/notices.mjs
import { build } from 'esbuild';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

async function bundledPackages(entry, platform) {
  const { metafile } = await build({
    entryPoints: [join(root, entry)],
    bundle: true,
    platform,
    external: ['vscode'],
    define: { MERMAID_VERSION: '"x"' },
    write: false,
    metafile: true,
    logLevel: 'silent',
  });
  const names = new Set();
  for (const input of Object.keys(metafile.inputs)) {
    const match = /node_modules\/((?:@[^/]+\/)?[^/]+)/.exec(input);
    if (match) {
      names.add(match[1]);
    }
  }
  return names;
}

function licenseText(dir) {
  const file = readdirSync(dir).find((name) => /^(licen[cs]e|copying)(\.|$)/i.test(name));
  return file ? readFileSync(join(dir, file), 'utf8').trim() : undefined;
}

const packages = new Set([
  ...(await bundledPackages('src/extension.ts', 'node')),
  ...(await bundledPackages('src/webview/main.ts', 'browser')),
  'mermaid', // dist/mermaid/mermaid.min.js
]);

let out = `# Third-party notices

Markdown Translate Preview ships the following third-party software.
Generated by \`scripts/notices.mjs\`.

## Markdown Preview Enhanced and crossnote

Parts of the source code, the preview and code block themes (\`styles/\`)
and the vendored Prism build come from Markdown Preview Enhanced and
crossnote by Yiyi Wang, University of Illinois/NCSA Open Source License.
See [LICENSE.md](LICENSE.md) and [UPSTREAM.md](UPSTREAM.md).

## Prism 1.30.0 (src/vendor/prism/prism.js)

MIT License, Copyright (c) 2012 Lea Verou. https://github.com/PrismJS/prism

Several code block themes in \`styles/prism_theme\` are community Prism
themes and keep their original author headers.
`;

for (const name of [...packages].sort()) {
  const dir = join(root, 'node_modules', name);
  if (!existsSync(dir)) {
    continue;
  }
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  const text = licenseText(dir) ?? `License: ${pkg.license}`;
  out += `\n## ${pkg.name} ${pkg.version} (${pkg.license})\n\n${
    pkg.homepage ?? pkg.repository?.url ?? ''
  }\n\n\`\`\`text\n${text}\n\`\`\`\n`;
}

writeFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), out);
console.log(`THIRD_PARTY_NOTICES.md: ${packages.size} packages`);
