// Regenerates THIRD_PARTY_NOTICES.md from the licenses of the packages that
// end up in dist/ (bundled code and copied assets). Run: node scripts/notices.mjs
import { build } from 'esbuild';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

async function bundledPackages(entry, platform) {
  const { metafile } = await build({
    entryPoints: [join(root, entry)],
    bundle: true,
    platform,
    external: ['vscode'],
    write: false,
    metafile: true,
    logLevel: 'silent',
  });
  const names = new Set();
  for (const input of Object.keys(metafile.inputs)) {
    const match = /node_modules\/((?:@[^/]+\/)?[^/]+)/.exec(input);
    if (match) {
      names.add(match[1]);
    }
  }
  return names;
}

function licenseText(dir) {
  const file = readdirSync(dir).find((name) => /^(licen[cs]e|copying)(\.|$)/i.test(name));
  return file ? readFileSync(join(dir, file), 'utf8').trim() : undefined;
}

const packages = new Set([
  ...(await bundledPackages('src/extension.ts', 'node')),
  ...(await bundledPackages('src/webview/main.ts', 'browser')),
  'mermaid', // dist/mermaid/mermaid.min.js
  '@browsermt/bergamot-translator', // dist/bergamot/ (worker + WASM)
]);

let out = `# Third-party notices

Folio ships the following third-party software.
Generated by \`scripts/notices.mjs\`.

## Markdown Preview Enhanced and crossnote

Parts of the source code, the preview and code block themes (\`styles/\`)
and the vendored Prism build come from Markdown Preview Enhanced and
crossnote by Yiyi Wang, University of Illinois/NCSA Open Source License.
See [LICENSE.md](LICENSE.md) and [UPSTREAM.md](UPSTREAM.md).

## Prism 1.30.0 (src/vendor/prism/prism.js)

MIT License, Copyright (c) 2012 Lea Verou. https://github.com/PrismJS/prism

Several code block themes in \`styles/prism_theme\` are community Prism
themes and keep their original author headers.

## Material Icons (settings icon in src/webview/quickSettings.ts)

Apache License 2.0, Copyright Google. https://github.com/google/material-design-icons

## Bergamot translator (dist/bergamot/, src/vendor/bergamot/translator.js)

Mozilla Public License 2.0. Source code: https://github.com/browsermt/bergamot-translator
(npm package @browsermt/bergamot-translator 0.4.9). \`translator.js\` is
included in modified form; the modifications are described in its header.
License text: https://mozilla.org/MPL/2.0/

## Translation models (not included)

The offline translation models are not part of this extension. They are
downloaded on request from the Bergamot project
(https://github.com/browsermt/students) and are licensed under
Creative Commons Attribution-ShareAlike 4.0
(https://creativecommons.org/licenses/by-sa/4.0/). The model list in
\`src/translation/offline/models.json\` comes from
https://bergamot.s3.amazonaws.com/models/index.json.

## Dictionaries (not included)

The dictionaries used for the other meanings of a single word are not part
of this extension. They are downloaded on request from WikDict
(https://www.wikdict.com), which builds them from Wiktionary
(https://www.wiktionary.org) through DBnary; they are licensed under
Creative Commons Attribution-ShareAlike 3.0
(https://creativecommons.org/licenses/by-sa/3.0/). The tooltip credits
Wiktionary next to the meanings.
`;

for (const name of [...packages].sort()) {
  const dir = join(root, 'node_modules', name);
  if (!existsSync(dir)) {
    continue;
  }
  const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
  const text = licenseText(dir) ?? `License: ${pkg.license}`;
  out += `\n## ${pkg.name} ${pkg.version} (${pkg.license})\n\n${
    pkg.homepage ?? pkg.repository?.url ?? ''
  }\n\n\`\`\`text\n${text}\n\`\`\`\n`;
}

writeFileSync(join(root, 'THIRD_PARTY_NOTICES.md'), out);
console.log(`THIRD_PARTY_NOTICES.md: ${packages.size} packages`);
